FROM node:25.9.0-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4 AS build
LABEL org.opencontainers.image.source="https://github.com/4ks-io/4ks"
RUN apk --no-cache add git bash
RUN npm install -g pnpm@10.28.0

WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

FROM build

WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

COPY ./libs/reserved-words ./apps/web/public
COPY ./libs/ts/api-fetch ./libs/ts/api-fetch
RUN pnpm --filter @4ks/api-fetch build

COPY ./apps/web ./apps/web

# RUN pnpm --filter @4ks/web build
# CMD [ "pnpm", "--filter", "@4ks/web", "start" ]

CMD [ "pnpm", "--filter", "@4ks/web", "dev" ]
EXPOSE 3000
