#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_ENV_FILE="${ROOT_DIR}/dev/secrets/local.env"

if [[ ! -f "${SECRETS_ENV_FILE}" ]]; then
  echo "missing ${SECRETS_ENV_FILE}; copy dev/secrets/local.env.example first" >&2
  exit 1
fi

set -a
source "${SECRETS_ENV_FILE}"
set +a

required_vars=(
  GOOGLE_APPLICATION_CREDENTIALS
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" || "${!var_name}" == "replace-me" ]]; then
    echo "${var_name} must be set in dev/secrets/local.env" >&2
    exit 1
  fi
done

AUTH0_CLIENT_SECRET_VALUE="${AUTH0_CLIENT_SECRET:-}"
if [[ -z "${AUTH0_CLIENT_SECRET_VALUE}" || "${AUTH0_CLIENT_SECRET_VALUE}" == "replace-me" ]]; then
  AUTH0_CLIENT_SECRET_VALUE="local-auth0-client-secret"
  echo "warning: using placeholder AUTH0_CLIENT_SECRET for local web bootstrap" >&2
fi

AUTH0_SECRET_VALUE="${AUTH0_SECRET:-}"
if [[ -z "${AUTH0_SECRET_VALUE}" || "${AUTH0_SECRET_VALUE}" == "replace-me" ]]; then
  AUTH0_SECRET_VALUE="local-auth0-session-secret"
  echo "warning: using placeholder AUTH0_SECRET for local web bootstrap" >&2
fi

GOOGLE_CREDS_FILE="${ROOT_DIR}/${GOOGLE_APPLICATION_CREDENTIALS}"
if [[ ! -f "${GOOGLE_CREDS_FILE}" ]]; then
  echo "missing ${GOOGLE_CREDS_FILE}; add the local Google service account JSON before starting Tilt" >&2
  exit 1
fi

kubectl create secret generic web-local-secrets \
  --from-literal=AUTH0_CLIENT_SECRET="${AUTH0_CLIENT_SECRET_VALUE}" \
  --from-literal=AUTH0_SECRET="${AUTH0_SECRET_VALUE}" \
  --dry-run=client \
  -o yaml | kubectl apply -f -

kubectl create secret generic api-google-app-creds \
  --from-file=google-app-creds.json="${GOOGLE_CREDS_FILE}" \
  --dry-run=client \
  -o yaml | kubectl apply -f -

cat > "${ROOT_DIR}/utils/media-update/local.env" <<EOF
# Generated by dev/bootstrap-secrets.sh
debug: false
batch_size: 10
max_files: 0
project_id: ${GOOGLE_CLOUD_PROJECT:-dev-4ks}

# firestore
fire_database_id: "${FIRESTORE_DATABASE_ID:-(default)}"
fire_collection_name: recipe-medias
EOF

cat > "${ROOT_DIR}/utils/recipe-update/local.env" <<EOF
# Generated by dev/bootstrap-secrets.sh
debug: false
dry_run: true
batch_size: 10
max_files: 0
project_id: ${GOOGLE_CLOUD_PROJECT:-dev-4ks}

# firestore
fire_database_id: "${FIRESTORE_DATABASE_ID:-(default)}"
fire_collection_name: recipes
EOF

cat > "${ROOT_DIR}/utils/recipe-search-refresh/local.env" <<EOF
# Generated by dev/bootstrap-secrets.sh
debug: false
dry_run: true
batch_size: 10
max_files: 0
project_id: ${GOOGLE_CLOUD_PROJECT:-dev-4ks}

# firestore
fire_database_id: "${FIRESTORE_DATABASE_ID:-(default)}"
fire_collection_name: recipes

# typesense
typesense_url: ${TYPESENSE_URL:-http://typesense.default.svc.cluster.local:8108}
typesense_key: ${TYPESENSE_API_KEY:-local-4ks-api-key}
EOF

echo "updated kubernetes secrets and generated utils/*/local.env"
