FROM golang:1.26.2-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1 AS build
LABEL org.opencontainers.image.source="https://github.com/4ks-io/4ks"
RUN apk --no-cache add curl busybox-extras
RUN go install github.com/mitranim/gow@latest

WORKDIR /code
COPY ./apps/fetcher/go.mod ./
COPY ./apps/fetcher/go.sum ./
RUN go mod download

FROM build

WORKDIR /code
COPY ./apps/fetcher ./
RUN go mod tidy

CMD ["gow", "run",  "./cmd"]
