apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: web
          env:
            - name: IO_4KS_API_URL
              value: http://api.default.svc.cluster.local
            - name: LOG_DEBUG
              value: 'true'
            - name: APP_BASE_URL
              value: https://local.4ks.io
            - name: AUTH0_CLIENT_ID
              value: eM5Zyyfp6coLg3zORMFsZEnQmpqxBjHd
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-local-secrets
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_DOMAIN
              value: 4ks-dev.us.auth0.com
            - name: AUTH0_AUDIENCE
              value: https://local.4ks.io/api
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-local-secrets
                  key: AUTH0_SECRET
            - name: TYPESENSE_URL_CLIENT
              value: local.4ks.io
            - name: TYPESENSE_PATH_CLIENT
              value: /search
            - name: TYPESENSE_API_KEY
              value: local-4ks-api-key
            - name: MEDIA_FALLBACK_URL
              value: https://local.4ks.io/static/fallback
            - name: TYPESENSE_URL
              value: typesense.default.svc.cluster.local
            - name: TYPESENSE_PROTOCOL
              value: http
            - name: TYPESENSE_PORT
              value: '8108'
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     port: 3000
          #     path: '/'
