FROM golang:1.26.2-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1 AS build
LABEL org.opencontainers.image.source="https://github.com/4ks-io/4ks"
RUN apk --no-cache add curl busybox-extras
RUN go install github.com/mitranim/gow@latest

WORKDIR /code
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

FROM build
WORKDIR /code
COPY ./libs/reserved-words/reserved-words ./reserved-words

COPY ./go.mod ./
COPY ./go.sum ./

COPY ./apps/api ./apps/api
COPY ./libs/go ./libs/go
RUN go mod tidy

CMD ["gow", "run", "./apps/api"]
