FROM golang:1.26.2-alpine@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1
LABEL org.opencontainers.image.source="https://github.com/4ks-io/4ks"
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN go install github.com/mitranim/gow@latest

WORKDIR /code

COPY ./libs/reserved-words/reserved-words ./reserved-words
COPY ./go.mod ./
COPY ./go.sum ./
COPY ./apps/api ./apps/api
COPY ./libs/go ./libs/go

RUN go mod tidy
RUN go build ./apps/api/main.go

USER appuser
CMD ["/code/main"]
