name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'dev | tst | prd'
        required: true
        type: string
      build_number:
        description: 'build number'
        required: true
        type: string
      run_tag:
        description: 'github run tag'
        required: true
        type: string
      workload_identity_provider:
        description: 'GCP Workload Identity Provider resource name'
        required: true
        type: string
      service_account:
        description: 'GCP service account email to impersonate'
        required: true
        type: string

jobs:
  api:
    uses: ./.github/workflows/build-container.yaml
    with:
      app_name: api
      # environment: ${{ inputs.environment }}
      gcp_project_name: eng-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ inputs.build_number }}
      run_tag: ${{ inputs.run_tag }}
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
  web:
    uses: ./.github/workflows/build-container.yaml
    with:
      app_name: web
      # environment: ${{ inputs.environment }}
      gcp_project_name: eng-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ inputs.build_number }}
      run_tag: ${{ inputs.run_tag }}
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
