name: review

on:
  workflow_call:
    inputs:
      environment:
        description: 'dev | tst | prd'
        required: false
        type: string
        default: dev

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: iac/app
    steps:
      - name: Manual Review
        uses: actions/github-script@v9
        with:
          script: core.setFailed('Manual review required')
